---
title: "Week 1 Discussion: Easter Island 🗿 "
---

```{r}
library(here)
library(tidyverse)
library(sf)
library(stars)
library(tmap)
```

read in data
```{r}
ei_points <- st_read(here("week1", "data", "ei_points.gpkg")) |> 
  filter(type == "volcano")
ei_elev <- read_stars(here("week1", "data", "ei_elev.tif"))
ei_borders <- st_read(here("week1", "data", "ei_border.gpkg"))
ei_roads <- st_read(here("week1", "data", "ei_roads.gpkg"))
```


Create a single-object map with tmap
```{r}
tm_shape(ei_borders) +
    tm_borders() +
    tm_title("Easter Island")
```

Create a multiple-object map with tmap
```{r}
easter_map <- tm_shape(ei_elev) +
    tm_graticules() +
    tm_raster(col.scale = tm_scale_continuous(values = "-rd_yl_gn"),
        col.legend = tm_legend("Elevation (m asl)")) +
    tm_shape(ei_borders) +
        tm_borders()+
    tm_shape(ei_roads) +
        tm_lines() +
    tm_shape(ei_points) +
        tm_symbols(shape = 24, size = "elevation", size.legend = tm_legend("Volcanoes (m asl)")) +
    tm_compass(position = c("right", "top")) +
    tm_scalebar() +
    tm_title(" 🗿 Easter Island 🗿 ")

easter_map

```

Create an interactive map with tmap
```{r}
tmap_mode("view")
easter_map
```


Create a multiple-object map with ggplot2
```{r}
library(ggplot2)
library(ggspatial)
```

```{r}
# extract lat & long from geom column 
volcanoes_point <- ei_points %>%
  mutate(lon = unlist(map(ei_points$geom,1)), # longitude = first component (x)
         lat = unlist(map(ei_points$geom,2))) # latitude = second component (y)
```


```{r}
ggplot() +
    geom_sf(data=ei_borders, color = "blue") +
    geom_stars(data = ei_elev) +
    scale_fill_distiller(name = "Elevation (m asl)",
                       palette = "RdYlGn",
                       na.value = "lightblue") +
    geom_sf(data = ei_roads, color = "#343a40") +
     geom_point(data = volcanoes_point, 
             aes(x = lon, y = lat, size = elevation),
             shape = 17, color = "#22577a") + 
    scale_size_continuous(name = "Volcanoes (m asl)") +
    ggspatial::annotation_north_arrow(location = "br", which_north = "true") +
    ggspatial::annotation_scale(location = "bl", width_hint = 0.5) +  
    labs(title = "Easter Island") +
    theme_minimal()

```